/**
 * @packageDocumentation
 * @module api.functional.shoppings.sellers.deliveries
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { tags } from "typia";

import type { IPage } from "../../../../structures/common/IPage";
import type { IShoppingDelivery } from "../../../../structures/shoppings/orders/IShoppingDelivery";
import type { IShoppingDeliveryPiece } from "../../../../structures/shoppings/orders/IShoppingDeliveryPiece";

export * as journeys from "./journeys";
export * as shippers from "./shippers";

/**
 * Get list of deliveries.
 *
 * Get list of {@link IShoppingDelivery.IInvert deliveries} of current
 * {@link IShoppingSeller seller} with {@link IPage pagination}.
 *
 * For reference, returned deliveries are containing the target
 * {@link IShoppingOrder.IInvertFromDelivery order} information. Of course,
 * only related {@link IShoppingOrderGood goods} are contained in the orders.
 *
 * Additionally, you can limit the result by configuring
 * {@link IShoppingDelivery.IRequest.search search condition} in the request
 * body. Also, it is possible to customize sequence order of records by
 * configuring {@link IShoppingDelivery.IRequest.sort sort condition}.
 *
 * @param input Request info of pagination, searching and sorting
 * @returns Paginated deliveries
 * @tag Order
 * @author Samchon
 *
 * @controller ShoppingSellerDeliveryController.index
 * @path PATCH /shoppings/sellers/deliveries
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  input: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    input,
  );
}
export namespace index {
  export type Body = IShoppingDelivery.IRequest;
  export type Output = IPage<IShoppingDelivery.IInvert>;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppings/sellers/deliveries",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/shoppings/sellers/deliveries";
}

/**
 * Get a delivery.
 *
 * Get a {@link IShoppingDelivery.IInvert delivery} information with its ID.
 *
 * For reference, returned delivery is containing the target
 * {@link IShoppingOrder.IInvertFromDelivery order} information. Of course,
 * only related {@link IShoppingOrderGood goods} are contained in the orders.
 *
 * @param id Target delivery's {@link IShoppingDelivery.id }
 * @returns Delivery info with target orders
 * @tag Order
 * @author Samchon
 *
 * @controller ShoppingSellerDeliveryController.at
 * @path GET /shoppings/sellers/deliveries/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(id),
  });
}
export namespace at {
  export type Output = IShoppingDelivery.IInvert;

  export const METADATA = {
    method: "GET",
    path: "/shoppings/sellers/deliveries/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/shoppings/sellers/deliveries/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * Create a delivery.
 *
 * Create a {@link IShoppingDelivery delivery} record targeting
 * {@link IShoppingOrder orders}, their {@link IShoppingOrderGood goods} and
 * {@link IShoppingSaleUnitStock stocks} ({@link IShoppingDeliveryPiece}) with
 * {@link IShoppingDeliveryJourney journeys} and
 * {@link IShoppingDeliveryShipper shippers} info.
 *
 * Note that, composition of the {@link IShoppingDeliveryPiece} must not over
 * the required. To identify which pieces are required, recommend to call
 * the {@link incompletes} function with target orders'
 * {@link IShoppingOrderPublish.id}s before calling this one.
 *
 * @param input Creation info of delivery
 * @returns Newly created delivery
 * @tag Order
 * @author Samchon
 *
 * @controller ShoppingSellerDeliveryController.create
 * @path POST /shoppings/sellers/deliveries
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  input: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    input,
  );
}
export namespace create {
  export type Body = IShoppingDelivery.ICreate;
  export type Output = IShoppingDelivery;

  export const METADATA = {
    method: "POST",
    path: "/shoppings/sellers/deliveries",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/shoppings/sellers/deliveries";
}

/**
 * Get list of incomplete pieces.
 *
 * Get list of {@link IShoppingDeliveryPiece incomplete pieces} of target
 * orders' {@link IShoppingOrderPublish.id}s.
 *
 * If you specify target orders' publish IDs, then this function returns
 * incompleted pieces of the orders with computation as an Array of
 * {@link IShoppingDeliveryPiece.ICreate} type.
 *
 * You can utilize the result to make a huge {@link IShoppingDelivery delivery}
 * for integrated delivering, and also possible to make multiple deliveries for
 * split delivering.
 *
 * @param input List of target orders' {@link IShoppingOrderPublish.id }s
 * @returns List of incomplete pieces
 * @tag Order
 * @author Samchon
 *
 * @controller ShoppingSellerDeliveryController.incompletes
 * @path PATCH /shoppings/sellers/deliveries/incompletes
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function incompletes(
  connection: IConnection,
  input: incompletes.Body,
): Promise<incompletes.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...incompletes.METADATA,
      template: incompletes.METADATA.path,
      path: incompletes.path(),
    },
    input,
  );
}
export namespace incompletes {
  export type Body = IShoppingDeliveryPiece.IRequest;
  export type Output = IShoppingDeliveryPiece.ICreate[];

  export const METADATA = {
    method: "PATCH",
    path: "/shoppings/sellers/deliveries/incompletes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/shoppings/sellers/deliveries/incompletes";
}
