/**
 * @packageDocumentation
 * @module api.functional.shoppings.sellers.deliveries.journeys
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, Primitive } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { Format } from "typia/lib/tags/Format";

import type { IShoppingDeliveryJourney } from "../../../../../structures/shoppings/orders/IShoppingDeliveryJourney";
import { NestiaSimulator } from "../../../../../utils/NestiaSimulator";

/**
 * @controller ShoppingSellerDeliveryJourneysController.create
 * @path POST /shoppings/sellers/deliveries/:deliveryId/journeys
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
    connection: IConnection,
    deliveryId: string & Format<"uuid">,
    input: create.Input,
): Promise<create.Output> {
    return !!connection.simulate
        ? create.simulate(
              connection,
              deliveryId,
              input,
          )
        : PlainFetcher.fetch(
              {
                  ...connection,
                  headers: {
                      ...(connection.headers ?? {}),
                      "Content-Type": "application/json",
                  },
              },
              {
                  ...create.METADATA,
                  path: create.path(deliveryId),
              } as const,
              input,
          );
}
export namespace create {
    export type Input = Primitive<IShoppingDeliveryJourney.ICreate>;
    export type Output = Primitive<IShoppingDeliveryJourney>;

    export const METADATA = {
        method: "POST",
        path: "/shoppings/sellers/deliveries/:deliveryId/journeys",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (deliveryId: string & Format<"uuid">): string => {
        return `/shoppings/sellers/deliveries/${encodeURIComponent(deliveryId ?? "null")}/journeys`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Primitive<IShoppingDeliveryJourney> =>
        typia.random<Primitive<IShoppingDeliveryJourney>>(g);
    export const simulate = async (
        connection: IConnection,
        deliveryId: string & Format<"uuid">,
        input: create.Input,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(deliveryId),
            contentType: "application/json",
        });
        assert.param("deliveryId")(() => typia.assert(deliveryId));
        assert.body(() => typia.assert(input));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}

/**
 * @controller ShoppingSellerDeliveryJourneysController.complete
 * @path PUT /shoppings/sellers/deliveries/:deliveryId/journeys/:id/complete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function complete(
    connection: IConnection,
    deliveryId: string & Format<"uuid">,
    id: string & Format<"uuid">,
    input: complete.Input,
): Promise<void> {
    return !!connection.simulate
        ? complete.simulate(
              connection,
              deliveryId,
              id,
              input,
          )
        : PlainFetcher.fetch(
              {
                  ...connection,
                  headers: {
                      ...(connection.headers ?? {}),
                      "Content-Type": "application/json",
                  },
              },
              {
                  ...complete.METADATA,
                  path: complete.path(deliveryId, id),
              } as const,
              input,
          );
}
export namespace complete {
    export type Input = Primitive<IShoppingDeliveryJourney.IComplete>;

    export const METADATA = {
        method: "PUT",
        path: "/shoppings/sellers/deliveries/:deliveryId/journeys/:id/complete",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (deliveryId: string & Format<"uuid">, id: string & Format<"uuid">): string => {
        return `/shoppings/sellers/deliveries/${encodeURIComponent(deliveryId ?? "null")}/journeys/${encodeURIComponent(id ?? "null")}/complete`;
    }
    export const simulate = async (
        connection: IConnection,
        deliveryId: string & Format<"uuid">,
        id: string & Format<"uuid">,
        input: complete.Input,
    ): Promise<void> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(deliveryId, id),
            contentType: "application/json",
        });
        assert.param("deliveryId")(() => typia.assert(deliveryId));
        assert.param("id")(() => typia.assert(id));
        assert.body(() => typia.assert(input));
    }
}

/**
 * @controller ShoppingSellerDeliveryJourneysController.erase
 * @path DELETE /shoppings/sellers/deliveries/:deliveryId/journeys/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
    connection: IConnection,
    deliveryId: string & Format<"uuid">,
    id: string & Format<"uuid">,
): Promise<void> {
    return !!connection.simulate
        ? erase.simulate(
              connection,
              deliveryId,
              id,
          )
        : PlainFetcher.fetch(
              connection,
              {
                  ...erase.METADATA,
                  path: erase.path(deliveryId, id),
              } as const,
          );
}
export namespace erase {

    export const METADATA = {
        method: "DELETE",
        path: "/shoppings/sellers/deliveries/:deliveryId/journeys/:id",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (deliveryId: string & Format<"uuid">, id: string & Format<"uuid">): string => {
        return `/shoppings/sellers/deliveries/${encodeURIComponent(deliveryId ?? "null")}/journeys/${encodeURIComponent(id ?? "null")}`;
    }
    export const simulate = async (
        connection: IConnection,
        deliveryId: string & Format<"uuid">,
        id: string & Format<"uuid">,
    ): Promise<void> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(deliveryId, id),
            contentType: "application/json",
        });
        assert.param("deliveryId")(() => typia.assert(deliveryId));
        assert.param("id")(() => typia.assert(id));
    }
}