/**
 * @packageDocumentation
 * @module api.functional.shoppings.admins
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
export * as authenticate from "./authenticate";
export * as orders from "./orders";
export * as sales from "./sales";