/**
 * @packageDocumentation
 * @module api.functional.shoppings.admins
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as authenticate from "./authenticate/index";
export * as coupons from "./coupons/index";
export * as deposits from "./deposits/index";
export * as mileages from "./mileages/index";
export * as orders from "./orders/index";
export * as sales from "./sales/index";
export * as systematic from "./systematic/index";
