/**
 * @packageDocumentation
 * @module api.functional.shoppings.admins.authenticate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, Primitive } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IShoppingAdministrator } from "../../../../structures/shoppings/actors/IShoppingAdministrator";
import type { IShoppingMember } from "../../../../structures/shoppings/actors/IShoppingMember";
import { NestiaSimulator } from "../../../../utils/NestiaSimulator";

/**
 * @controller ShoppingAdminAuthenticateController.get
 * @path GET /shoppings/admins/authenticate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
    connection: IConnection,
): Promise<get.Output> {
    return !!connection.simulate
        ? get.simulate(
              connection,
          )
        : PlainFetcher.fetch(
              connection,
              {
                  ...get.METADATA,
                  path: get.path(),
              } as const,
          );
}
export namespace get {
    export type Output = Primitive<IShoppingAdministrator.IInvert>;

    export const METADATA = {
        method: "GET",
        path: "/shoppings/admins/authenticate",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/shoppings/admins/authenticate`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Primitive<IShoppingAdministrator.IInvert> =>
        typia.random<Primitive<IShoppingAdministrator.IInvert>>(g);
    export const simulate = async (
        connection: IConnection,
    ): Promise<Output> => {
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}

/**
 * @controller ShoppingAdminAuthenticateController.join
 * @path POST /shoppings/admins/authenticate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function join(
    connection: IConnection,
    input: join.Input,
): Promise<join.Output> {
    return !!connection.simulate
        ? join.simulate(
              connection,
              input,
          )
        : PlainFetcher.fetch(
              {
                  ...connection,
                  headers: {
                      ...(connection.headers ?? {}),
                      "Content-Type": "application/json",
                  },
              },
              {
                  ...join.METADATA,
                  path: join.path(),
              } as const,
              input,
          );
}
export namespace join {
    export type Input = Primitive<IShoppingAdministrator.IJoin>;
    export type Output = Primitive<IShoppingAdministrator.IInvert>;

    export const METADATA = {
        method: "POST",
        path: "/shoppings/admins/authenticate",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/shoppings/admins/authenticate`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Primitive<IShoppingAdministrator.IInvert> =>
        typia.random<Primitive<IShoppingAdministrator.IInvert>>(g);
    export const simulate = async (
        connection: IConnection,
        input: join.Input,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(),
            contentType: "application/json",
        });
        assert.body(() => typia.assert(input));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}

/**
 * @controller ShoppingAdminAuthenticateController.login
 * @path PUT /shoppings/admins/authenticate/login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
    connection: IConnection,
    input: login.Input,
): Promise<login.Output> {
    return !!connection.simulate
        ? login.simulate(
              connection,
              input,
          )
        : PlainFetcher.fetch(
              {
                  ...connection,
                  headers: {
                      ...(connection.headers ?? {}),
                      "Content-Type": "application/json",
                  },
              },
              {
                  ...login.METADATA,
                  path: login.path(),
              } as const,
              input,
          );
}
export namespace login {
    export type Input = Primitive<IShoppingMember.ILogin>;
    export type Output = Primitive<IShoppingAdministrator.IInvert>;

    export const METADATA = {
        method: "PUT",
        path: "/shoppings/admins/authenticate/login",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/shoppings/admins/authenticate/login`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Primitive<IShoppingAdministrator.IInvert> =>
        typia.random<Primitive<IShoppingAdministrator.IInvert>>(g);
    export const simulate = async (
        connection: IConnection,
        input: login.Input,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(),
            contentType: "application/json",
        });
        assert.body(() => typia.assert(input));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}