/**
 * @packageDocumentation
 * @module api.functional.shoppings.admins.authenticate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IShoppingAdministrator } from "../../../../structures/shoppings/actors/IShoppingAdministrator";
import type { IShoppingMember } from "../../../../structures/shoppings/actors/IShoppingMember";

/**
 * Get administrator information.
 *
 * Get {@link IShoppingAdministrator.IInvert administrator} information of
 * current {@link IShoppingCustomer customer}.
 *
 * If current {@link IShoppingMember member} is not an administrator,
 * it throws 403 forbidden exception.
 *
 * @returns Admin info
 * @tag Authenticate
 * @author Samchon
 *
 * @controller ShoppingAdminAuthenticateController.get
 * @path GET /shoppings/admins/authenticate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(connection: IConnection): Promise<get.Output> {
  return PlainFetcher.fetch(connection, {
    ...get.METADATA,
    template: get.METADATA.path,
    path: get.path(),
  });
}
export namespace get {
  export type Output = IShoppingAdministrator.IInvert;

  export const METADATA = {
    method: "GET",
    path: "/shoppings/admins/authenticate",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/shoppings/admins/authenticate";
}

/**
 * Join as an administrator.
 *
 * Join as an administrator with {@link IShoppingAdministrator.IJoin joining info}.
 *
 * This method is allowed only when the {@link IShoppingCustomer customer} already
 * has joined the {@link IShoppingMember membership}. IF not, he (she) must
 * accomplish it before. If not, 403 forbidden exception would be thrown.
 *
 * @param input Joining request info
 * @returns Administrator info
 * @tag Authenticate
 * @todo Need to add approval process
 * @author Samchon
 *
 * @controller ShoppingAdminAuthenticateController.join
 * @path POST /shoppings/admins/authenticate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function join(
  connection: IConnection,
  input: join.Body,
): Promise<join.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...join.METADATA,
      template: join.METADATA.path,
      path: join.path(),
    },
    input,
  );
}
export namespace join {
  export type Body = IShoppingAdministrator.IJoin;
  export type Output = IShoppingAdministrator.IInvert;

  export const METADATA = {
    method: "POST",
    path: "/shoppings/admins/authenticate",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/shoppings/admins/authenticate";
}

/**
 * Login as an administrator.
 *
 * Login as an administrator with {@link IShoppingAdministrator.ILogin login info}.
 *
 * This method has exactly same effect with
 * {@link ShoppingApi.functional.customers.authenticate.login} function, but
 * returned type is a llttle different. The similar function returns
 * {@link IShoppingCustomer} type that starting from the customer information, so
 * that you have to access to the administrator info through
 * `customer.member.administrator`. In contrast with that, this method returns
 * {@link IShoppingAdministrator.IInvert} type that starting from the administrator
 * info, so that can access to the customer info through `administrator.customer`.
 *
 * Of course, to use this function, you had to {@link join} as an administrator
 * before. If not, 403 forbidden exception would be thrown,
 *
 * @param input Login request info
 * @returns Administrator info
 * @tag Authenticate
 * @author Samchon
 *
 * @controller ShoppingAdminAuthenticateController.login
 * @path PUT /shoppings/admins/authenticate/login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  input: login.Body,
): Promise<login.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...login.METADATA,
      template: login.METADATA.path,
      path: login.path(),
    },
    input,
  );
}
export namespace login {
  export type Body = IShoppingMember.ILogin;
  export type Output = IShoppingAdministrator.IInvert;

  export const METADATA = {
    method: "PUT",
    path: "/shoppings/admins/authenticate/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/shoppings/admins/authenticate/login";
}
