/**
 * @packageDocumentation
 * @module api.functional.shoppings.sellers.systematic.channels
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { Format } from "typia/lib/tags/Format";

import type { IPage } from "../../../../../structures/common/IPage";
import type { IShoppingChannel } from "../../../../../structures/shoppings/systematic/IShoppingChannel";

export * as categories from "./categories";

/**
 * List up every channels.
 *
 * List up every {@link IShoppingChannel channels} with pagination.
 *
 * If you want, you can limit the result by configuring
 * {@link IShoppingChannel.IRequest.search search condition} in the request
 * body. Also, it is possible to customize sequence order of records by
 * configuring {@link IShoppingChannel.IRequest.sort sort condition}.
 *
 * @param input Request info of pagination, searching and sorting
 * @returns Paginated channels
 * @tag Systematic
 * @author Samchon
 *
 * @controller ShoppingSellerSystematicChannelController.index
 * @path PATCH /shoppings/sellers/systematic/channels
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  input: IShoppingChannel.IRequest,
): Promise<index.Output> {
  return !!connection.simulate
    ? index.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          template: index.METADATA.path,
          path: index.path(),
        },
        input,
      );
}
export namespace index {
  export type Input = IShoppingChannel.IRequest;
  export type Output = IPage<IShoppingChannel>;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppings/sellers/systematic/channels",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/shoppings/sellers/systematic/channels";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): IPage<IShoppingChannel> => typia.random<IPage<IShoppingChannel>>(g);
  export const simulate = (
    connection: IConnection,
    input: IShoppingChannel.IRequest,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * List up every channels with nested categories.
 *
 * List up every {@link IShoppingChannel.IHierarchical channels} with
 * {@link IPage pagination}. Returned channels contain nested hierarchical
 * {@link IShoppingChannelCategory.IHierarchical categories}.
 *
 * If you want, you can limit the result by configuring
 * {@link IShoppingChannel.IRequest.search search condition} in the request
 * body. Also, it is possible to customize sequence order of records by
 * configuring {@link IShoppingChannel.IRequest.sort sort condition}.
 *
 * @param input Request info of pagination, searching and sorting
 * @returns Paginated channels with nested categories
 * @tag Systematic
 * @author Samchon
 *
 * @controller ShoppingSellerSystematicChannelController.hierarchical
 * @path PATCH /shoppings/sellers/systematic/channels/hierarchical
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function hierarchical(
  connection: IConnection,
  input: IShoppingChannel.IRequest,
): Promise<hierarchical.Output> {
  return !!connection.simulate
    ? hierarchical.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...hierarchical.METADATA,
          template: hierarchical.METADATA.path,
          path: hierarchical.path(),
        },
        input,
      );
}
export namespace hierarchical {
  export type Input = IShoppingChannel.IRequest;
  export type Output = IPage<IShoppingChannel.IHierarchical>;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppings/sellers/systematic/channels/hierarchical",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () =>
    "/shoppings/sellers/systematic/channels/hierarchical";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): IPage<IShoppingChannel.IHierarchical> =>
    typia.random<IPage<IShoppingChannel.IHierarchical>>(g);
  export const simulate = (
    connection: IConnection,
    input: IShoppingChannel.IRequest,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Get a channel info.
 *
 * Get a detailed {@link IShoppingChannel.IHierarchical channel} information.
 *
 * Returned channel instance also contains the nested
 * {@link IShoppingChannelCategory.IHierarchical hierarchical category}
 * informations.
 *
 * @param id Target channel's {@link IShoppingChannel.id}
 * @returns Detailed channel info
 * @tag Systematic
 * @author Samchon
 *
 * @controller ShoppingSellerSystematicChannelController.at
 * @path GET /shoppings/sellers/systematic/channels/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<at.Output> {
  return !!connection.simulate
    ? at.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...at.METADATA,
        template: at.METADATA.path,
        path: at.path(id),
      });
}
export namespace at {
  export type Output = IShoppingChannel.IHierarchical;

  export const METADATA = {
    method: "GET",
    path: "/shoppings/sellers/systematic/channels/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/shoppings/sellers/systematic/channels/${encodeURIComponent(id ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): IShoppingChannel.IHierarchical =>
    typia.random<IShoppingChannel.IHierarchical>(g);
  export const simulate = (
    connection: IConnection,
    id: string & Format<"uuid">,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Get a channel info by its code.
 *
 * Get a detailed {@link IShoppingChannel.IHierarchical channel} information
 * by its code.
 *
 * Returned channel instance also contains the nested
 * {@link IShoppingChannelCategory.IHierarchical hierarchical category}
 * informations.
 *
 * @param code Target channel's {@link IShoppingChannel.code}
 * @returns Detailed channel info
 * @tag Systematic
 * @author Samchon
 *
 * @controller ShoppingSellerSystematicChannelController.get
 * @path GET /shoppings/sellers/systematic/channels/:code/get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
  connection: IConnection,
  code: string,
): Promise<get.Output> {
  return !!connection.simulate
    ? get.simulate(connection, code)
    : PlainFetcher.fetch(connection, {
        ...get.METADATA,
        template: get.METADATA.path,
        path: get.path(code),
      });
}
export namespace get {
  export type Output = IShoppingChannel.IHierarchical;

  export const METADATA = {
    method: "GET",
    path: "/shoppings/sellers/systematic/channels/:code/get",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (code: string) =>
    `/shoppings/sellers/systematic/channels/${encodeURIComponent(code ?? "null")}/get`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): IShoppingChannel.IHierarchical =>
    typia.random<IShoppingChannel.IHierarchical>(g);
  export const simulate = (connection: IConnection, code: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(code),
      contentType: "application/json",
    });
    assert.param("code")(() => typia.assert(code));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
