/**
 * @packageDocumentation
 * @module api.functional.shoppings.admins.mileages
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { Format } from "typia/lib/tags/Format";

import type { IPage } from "../../../../structures/common/IPage";
import type { IShoppingMileage } from "../../../../structures/shoppings/mileages/IShoppingMileage";

export * as donations from "./donations";

/**
 * Get mileage metadata list.
 *
 * List up every {@link IShoppingMileage mileage} metadata informations
 * with {@link IPage pagination}.
 *
 * If you want, you can limit the result by configuring
 * {@link IShoppingMileage.IRequest.search search condition} in the request body.
 * Also, it is possible to customize sequence order of records by configuring
 * {@link IShoppingMileage.IRequest.sort sort condition}.
 *
 * @param input Request info of pagination, searching and sorting
 * @returns Paginated mileage metadata list
 * @tag Discount
 * @author Samchon
 *
 * @controller ShoppingAdminMileageController.index
 * @path PATCH /shoppings/admins/mileages
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  input: index.Input,
): Promise<index.Output> {
  return !!connection.simulate
    ? index.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
        },
        input,
      );
}
export namespace index {
  export type Input = Primitive<IShoppingMileage.IRequest>;
  export type Output = Primitive<IPage<IShoppingMileage>>;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppings/admins/mileages",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/shoppings/admins/mileages";
  export const random = (g?: Partial<typia.IRandomGenerator>) =>
    typia.random<Primitive<IPage<IShoppingMileage>>>(g);
  export const simulate = (
    connection: IConnection,
    input: index.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Get a mileage metadata.
 *
 * Get a {@link IShoppingMileage mileage} metadata information with its ID.
 *
 * @param id Target mileage's {@link IShoppingMileage.id}
 * @returns Mileage metadata
 * @tag Discount
 * @author Samchon
 *
 * @controller ShoppingAdminMileageController.at
 * @path GET /shoppings/admins/mileages/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<at.Output> {
  return !!connection.simulate
    ? at.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...at.METADATA,
        path: at.path(id),
      });
}
export namespace at {
  export type Output = Primitive<IShoppingMileage>;

  export const METADATA = {
    method: "GET",
    path: "/shoppings/admins/mileages/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/shoppings/admins/mileages/${encodeURIComponent(id ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>) =>
    typia.random<Primitive<IShoppingMileage>>(g);
  export const simulate = (
    connection: IConnection,
    id: string & Format<"uuid">,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Get a mileage metadata by its code.
 *
 * Get a {@link IShoppingMileage mileage} metadata information with its code.
 *
 * @returns Mileage metadata
 * @tag Discount
 * @author Samchon
 *
 * @controller ShoppingAdminMileageController.get
 * @path GET /shoppings/admins/mileages/:code/get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
  connection: IConnection,
  code: string,
): Promise<get.Output> {
  return !!connection.simulate
    ? get.simulate(connection, code)
    : PlainFetcher.fetch(connection, {
        ...get.METADATA,
        path: get.path(code),
      });
}
export namespace get {
  export type Output = Primitive<IShoppingMileage>;

  export const METADATA = {
    method: "GET",
    path: "/shoppings/admins/mileages/:code/get",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (code: string) =>
    `/shoppings/admins/mileages/${encodeURIComponent(code ?? "null")}/get`;
  export const random = (g?: Partial<typia.IRandomGenerator>) =>
    typia.random<Primitive<IShoppingMileage>>(g);
  export const simulate = (connection: IConnection, code: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(code),
      contentType: "application/json",
    });
    assert.param("code")(() => typia.assert(code));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Create a new mileage metadata.
 *
 * Create a new {@link IShoppingMileage mileage} metadata.
 *
 * This action means that adding a new origin reason of mileage's income/outcome.
 * Of course, creating a new mileage record does not mean that automatically
 * increase or decrease the {@link IShoppingCustomer customer}'s balance
 * following the record's reason why. The logic must be developed manually
 * in the backend side.
 *
 * @param input Creation information of mileage metadata
 * @returns Newly created mileage metadata
 * @tag Discount
 * @author Samchon
 *
 * @controller ShoppingAdminMileageController.create
 * @path POST /shoppings/admins/mileages
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  input: create.Input,
): Promise<create.Output> {
  return !!connection.simulate
    ? create.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
        },
        input,
      );
}
export namespace create {
  export type Input = Primitive<IShoppingMileage.ICreate>;
  export type Output = Primitive<IShoppingMileage>;

  export const METADATA = {
    method: "POST",
    path: "/shoppings/admins/mileages",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/shoppings/admins/mileages";
  export const random = (g?: Partial<typia.IRandomGenerator>) =>
    typia.random<Primitive<IShoppingMileage>>(g);
  export const simulate = (
    connection: IConnection,
    input: create.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Erase a mileage metadata.
 *
 * Erase a {@link IShoppingMileage mileage} metadata, so that no more
 * {@link IShoppingCustomer customer}'s balance does not be increased or
 * decreased by the mileage's reason why.
 *
 * @param id Target mileage's {@link IShoppingMileage.id}
 * @tag Discount
 * @author Samchon
 *
 * @controller ShoppingAdminMileageController.erase
 * @path DELETE /shoppings/admins/mileages/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<void> {
  return !!connection.simulate
    ? erase.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...erase.METADATA,
        path: erase.path(id),
      });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/shoppings/admins/mileages/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/shoppings/admins/mileages/${encodeURIComponent(id ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>) =>
    typia.random<Primitive<void>>(g);
  export const simulate = (
    connection: IConnection,
    id: string & Format<"uuid">,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
