/**
 * @packageDocumentation
 * @module api.functional.shoppings.customers.carts.commodities
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import typia from "typia";
import type { tags } from "typia";

import type { IPage } from "../../../../../structures/common/IPage";
import type { IShoppingCartCommodity } from "../../../../../structures/shoppings/orders/IShoppingCartCommodity";
import type { IShoppingCartDiscountable } from "../../../../../structures/shoppings/orders/IShoppingCartDiscountable";

/**
 * List of every commodities.
 *
 * List up every {@link IShoppingCartCommodity commodities} in the
 * shopping cart with {@link IPage pagination}.
 *
 * You can limit the result by configuring
 * {@link IShoppingCartCommodity.IRequest.search search condition} in the
 * request body. Furthermore, it is possible to customize sequence order of
 * records by configuring {@link IShoppingCartCommodity.IRequest.sort}.
 *
 * For reference, when some commodity be {@link IShoppingOrder ordered} and
 * {@link IShoppingOrderPublish published}, then it would not be appread in
 * the shopping cart more. Otherwise, the order has not been published yet,
 * it would be appread in the shopping cart and still enable to create a new
 * {@link IShoppingOrder order application} with the same commodity.
 *
 * Of course, if the target {@link IShoppingSale sale} has been suspended, or
 * {@link IShoppingSaleUnitStockInventory out of stock}, then it would not be
 * appread in the shopping cart more, either.
 *
 * @param input Request info of pagination, searching and sorting
 * @returns Paginated commodities
 * @tag Order
 * @author Samchon
 *
 * @controller ShoppingCustomerCartCommodityController.index
 * @path PATCH /shoppings/customers/carts/commodities
 * @accessor api.functional.shoppings.customers.carts.commodities.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  input: index.Body,
): Promise<index.Output> {
  return true === connection.simulate
    ? index.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          template: index.METADATA.path,
          path: index.path(),
        },
        input,
      );
}
export namespace index {
  export type Body = IShoppingCartCommodity.IRequest;
  export type Output = IPage<IShoppingCartCommodity>;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppings/customers/carts/commodities",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/shoppings/customers/carts/commodities";
  export const random = (): IPage<IShoppingCartCommodity> =>
    typia.random<IPage<IShoppingCartCommodity>>();
  export const simulate = (connection: IConnection, input: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random();
  };
}

/**
 * Get a commodity.
 *
 * Get a {@link IShoppingCartCommodity commodity} record of the shopping cart.
 *
 * If target {@link IShoppingSale sale} has been suspended or
 * {@link IShoppingSaleUnitStockInventory out of stock}, then 410 gone error
 * would be thrown. Therefore, even if you've created a commodity successfully
 * with the {@link create} method, it still can be failed when you access the
 * commodity with this {@link at} method.
 *
 * @param id Target commodity's {@link IShoppingCartCommodity.id }
 * @returns Detailed commodity info
 * @tag Order
 * @author Samchon
 *
 * @controller ShoppingCustomerCartCommodityController.at
 * @path GET /shoppings/customers/carts/commodities/:id
 * @accessor api.functional.shoppings.customers.carts.commodities.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return true === connection.simulate
    ? at.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...at.METADATA,
        template: at.METADATA.path,
        path: at.path(id),
      });
}
export namespace at {
  export type Output = IShoppingCartCommodity;

  export const METADATA = {
    method: "GET",
    path: "/shoppings/customers/carts/commodities/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/shoppings/customers/carts/commodities/${encodeURIComponent(id?.toString() ?? "null")}`;
  export const random = (): IShoppingCartCommodity =>
    typia.random<IShoppingCartCommodity>();
  export const simulate = (
    connection: IConnection,
    id: string & tags.Format<"uuid">,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random();
  };
}

/**
 * Create a new commodity.
 *
 * Create a new {@link IShoppingCartCommodity commodity} into a specific
 * shopping cart.
 *
 * If {@link IShoppingCartCommodity.ICreate.accumulate} has `true` value
 * and there's some same commodity that composed with same
 * {@link IShoppingSaleUnitStock.IInvert stocks and quantities},
 * then new commodity would not be created but the volume would be accumulated.
 *
 * By the way, if the target {@link IShoppingSale sale} has been suspended or
 * {@link IShoppingSaleUnitStockInventory out of stock}, then 410 gone error
 * would be thrown. Therefore, it would better to check the target sale and
 * {@link IShoppingSaleUnitStock stock}'s status before.
 *
 * @param input Creation info of the commodity
 * @returns Newly created commodity
 * @tag Order
 * @author Samchon
 *
 * @controller ShoppingCustomerCartCommodityController.create
 * @path POST /shoppings/customers/carts/commodities
 * @accessor api.functional.shoppings.customers.carts.commodities.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  input: create.Body,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        input,
      );
}
export namespace create {
  export type Body = IShoppingCartCommodity.ICreate;
  export type Output = IShoppingCartCommodity;

  export const METADATA = {
    method: "POST",
    path: "/shoppings/customers/carts/commodities",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/shoppings/customers/carts/commodities";
  export const random = (): IShoppingCartCommodity =>
    typia.random<IShoppingCartCommodity>();
  export const simulate = (connection: IConnection, input: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random();
  };
}

/**
 * Update a commodity (volume).
 *
 * Update a {@link IShoppingCartCommodity commodity}'s volume in the
 * shopping cart.
 *
 * If target {@link IShoppingSale sale} has been suspended or
 * {@link IShoppingSaleUnitStockInventory out of stock} suddenly, then 410
 * gone error would be thrown, either.
 *
 * @param id Target commodity's {@link IShoppingCartCommodity.id }
 * @param input Update info of the commodity (volume)
 * @tag Order
 * @author Samchon
 *
 * @controller ShoppingCustomerCartCommodityController.update
 * @path PUT /shoppings/customers/carts/commodities/:id
 * @accessor api.functional.shoppings.customers.carts.commodities.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
  input: update.Body,
): Promise<void> {
  return true === connection.simulate
    ? update.simulate(connection, id, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(id),
        },
        input,
      );
}
export namespace update {
  export type Body = IShoppingCartCommodity.IUpdate;

  export const METADATA = {
    method: "PUT",
    path: "/shoppings/customers/carts/commodities/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/shoppings/customers/carts/commodities/${encodeURIComponent(id?.toString() ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    id: string & tags.Format<"uuid">,
    input: Body,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    assert.body(() => typia.assert(input));
    return random();
  };
}

/**
 * Get replica of a commodity.
 *
 * Get a {@link IShoppingCartCommodity.ICreate} typed info of the target
 * commodity for replication.
 *
 * If target {@link IShoppingSale sale} has been suspended or
 * {@link IShoppingSaleUnitStockInventory out of stock} suddenly,
 * then 410 gone error would be thrown, either.
 *
 * @param id Target commodity's {@link IShoppingCartCommodity.id }
 * @returns Creation info of the commodity for replication
 * @tag Order
 * @author Samchon
 *
 * @controller ShoppingCustomerCartCommodityController.replica
 * @path GET /shoppings/customers/carts/commodities/:id/replica
 * @accessor api.functional.shoppings.customers.carts.commodities.replica
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function replica(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
): Promise<replica.Output> {
  return true === connection.simulate
    ? replica.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...replica.METADATA,
        template: replica.METADATA.path,
        path: replica.path(id),
      });
}
export namespace replica {
  export type Output = IShoppingCartCommodity.ICreate;

  export const METADATA = {
    method: "GET",
    path: "/shoppings/customers/carts/commodities/:id/replica",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/shoppings/customers/carts/commodities/${encodeURIComponent(id?.toString() ?? "null")}/replica`;
  export const random = (): IShoppingCartCommodity.ICreate =>
    typia.random<IShoppingCartCommodity.ICreate>();
  export const simulate = (
    connection: IConnection,
    id: string & tags.Format<"uuid">,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random();
  };
}

/**
 * Erase a commodity.
 *
 * Erase a {@link IShoppingCartCommodity commodity} from the shopping cart.
 *
 * If the commodity is on an {@link IShoppingOrder order} process, it is not
 * possible to erase it. Instead, if the order has been
 * {@link IShoppingOrderPublish published}, then it would not be appread in
 * the shopping cart more. If the order be erased, then you also can continue
 * erasinng the commodity, neither.
 *
 * @param id Target commodity's {@link IShoppingCartCommodity.id }
 * @returns Newly created commodity
 * @tag Order
 * @author Samchon
 *
 * @controller ShoppingCustomerCartCommodityController.erase
 * @path DELETE /shoppings/customers/carts/commodities/:id
 * @accessor api.functional.shoppings.customers.carts.commodities.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...erase.METADATA,
        template: erase.METADATA.path,
        path: erase.path(id),
      });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/shoppings/customers/carts/commodities/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/shoppings/customers/carts/commodities/${encodeURIComponent(id?.toString() ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    id: string & tags.Format<"uuid">,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random();
  };
}

/**
 * Get discountable info.
 *
 * Compute discountable features about the
 *  {@link IShoppingCartCommodity shopping cart} even including
 * non-carted {@link IShoppingSale sales}.
 *
 * Returned {@link IShoppingCartDiscountable} contains including
 * combinations of adjustable {@link IShoppingCoupon coupons},
 * withdrawable {@link IShoppingDepositHistory deposits} and
 * {@link IShoppingMileageHistory mileages}.
 *
 * If you want to know the discountable info about some specific sales
 * that have not been carted yet, specify the sales to the
 * {@link IShoppingCartDiscountable.pseudos} property with composing
 * {@link IShoppingCartCommodity.ICreate creation info of the commodities}.
 * Then, they would be included in the discountable info.
 *
 * @param input Request info for discountable
 * @returns Discountable info
 * @tag Order
 * @author Samchon
 *
 * @controller ShoppingCustomerCartCommodityController.discountable
 * @path PATCH /shoppings/customers/carts/commodities/discountable
 * @accessor api.functional.shoppings.customers.carts.commodities.discountable
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function discountable(
  connection: IConnection,
  input: discountable.Body,
): Promise<discountable.Output> {
  return true === connection.simulate
    ? discountable.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...discountable.METADATA,
          template: discountable.METADATA.path,
          path: discountable.path(),
        },
        input,
      );
}
export namespace discountable {
  export type Body = IShoppingCartDiscountable.IRequest;
  export type Output = IShoppingCartDiscountable;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppings/customers/carts/commodities/discountable",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () =>
    "/shoppings/customers/carts/commodities/discountable";
  export const random = (): IShoppingCartDiscountable =>
    typia.random<IShoppingCartDiscountable>();
  export const simulate = (connection: IConnection, input: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random();
  };
}
