/**
 * @packageDocumentation
 * @module api.functional.shoppings.customers.deposits.histories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { Format } from "typia/lib/tags/Format";

import type { IPage } from "../../../../../structures/common/IPage";
import type { IShoppingDepositHistory } from "../../../../../structures/shoppings/deposits/IShoppingDepositHistory";

/**
 * List up every deposit histories.
 *
 * List up every {@link IShoppingDepositHistory deposit histories} of the
 * {@link IShoppingCustomer customer} with {@link IPage pagination}.
 *
 * If you want, you can limit the result by configuring
 * {@link IShoppingDepositHistory.IRequest.search search condition} in the
 * request body. Also, it is possible to customize sequence order of records
 * by configuring {@link IShoppingDepositHistory.IRequest.sort sort condition}.
 *
 * @param input Request info of pagination, searching and sorting
 * @returns Paginated deposit histories
 * @tag Discount
 * @author Samchon
 *
 * @controller ShoppingCustomerDepositHistoryController.index
 * @path PATCH /shoppings/customers/deposits/histories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  input: IShoppingDepositHistory.IRequest,
): Promise<index.Output> {
  return !!connection.simulate
    ? index.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          template: index.METADATA.path,
          path: index.path(),
        },
        input,
      );
}
export namespace index {
  export type Input = IShoppingDepositHistory.IRequest;
  export type Output = IPage<IShoppingDepositHistory>;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppings/customers/deposits/histories",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/shoppings/customers/deposits/histories";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): IPage<IShoppingDepositHistory> =>
    typia.random<IPage<IShoppingDepositHistory>>(g);
  export const simulate = (
    connection: IConnection,
    input: IShoppingDepositHistory.IRequest,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Get a deposit history info.
 *
 * Get a {@link IShoppingDepositHistory deposit history} information.
 *
 * @returns Deposit history info
 * @tag Discount
 * @author Samchon
 *
 * @controller ShoppingCustomerDepositHistoryController.at
 * @path GET /shoppings/customers/deposits/histories/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<at.Output> {
  return !!connection.simulate
    ? at.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...at.METADATA,
        template: at.METADATA.path,
        path: at.path(id),
      });
}
export namespace at {
  export type Output = IShoppingDepositHistory;

  export const METADATA = {
    method: "GET",
    path: "/shoppings/customers/deposits/histories/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/shoppings/customers/deposits/histories/${encodeURIComponent(id?.toString() ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): IShoppingDepositHistory => typia.random<IShoppingDepositHistory>(g);
  export const simulate = (
    connection: IConnection,
    id: string & Format<"uuid">,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Get balance of the deposit.
 *
 * Get current balance of the deposit of the {@link IShoppingCustomer customer}.
 *
 * @returns Balance of the deposit
 * @tag Discount
 * @author Samchon
 *
 * @controller ShoppingCustomerDepositHistoryController.balance
 * @path GET /shoppings/customers/deposits/histories/balance
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function balance(
  connection: IConnection,
): Promise<balance.Output> {
  return !!connection.simulate
    ? balance.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...balance.METADATA,
        template: balance.METADATA.path,
        path: balance.path(),
      });
}
export namespace balance {
  export type Output = number;

  export const METADATA = {
    method: "GET",
    path: "/shoppings/customers/deposits/histories/balance",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/shoppings/customers/deposits/histories/balance";
  export const random = (g?: Partial<typia.IRandomGenerator>): number =>
    typia.random<number>(g);
  export const simulate = (connection: IConnection): Output => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
