/**
 * @packageDocumentation
 * @module api.functional.shoppings.admins.systematic.channels
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, Primitive } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { Format } from "typia/lib/tags/Format";

import type { IPage } from "../../../../../structures/common/IPage";
import type { IRecordMerge } from "../../../../../structures/common/IRecordMerge";
import type { IShoppingChannel } from "../../../../../structures/shoppings/systematic/IShoppingChannel";
import { NestiaSimulator } from "../../../../../utils/NestiaSimulator";

export * as categories from "./categories";

/**
 * @controller ShoppingAdminSystematicChannelsController.create
 * @path POST /shoppings/admins/systematic/channels
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
    connection: IConnection,
    input: create.Input,
): Promise<create.Output> {
    return !!connection.simulate
        ? create.simulate(
              connection,
              input,
          )
        : PlainFetcher.fetch(
              {
                  ...connection,
                  headers: {
                      ...(connection.headers ?? {}),
                      "Content-Type": "application/json",
                  },
              },
              {
                  ...create.METADATA,
                  path: create.path(),
              } as const,
              input,
          );
}
export namespace create {
    export type Input = Primitive<IShoppingChannel.ICreate>;
    export type Output = Primitive<IShoppingChannel>;

    export const METADATA = {
        method: "POST",
        path: "/shoppings/admins/systematic/channels",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/shoppings/admins/systematic/channels`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Primitive<IShoppingChannel> =>
        typia.random<Primitive<IShoppingChannel>>(g);
    export const simulate = async (
        connection: IConnection,
        input: create.Input,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(),
            contentType: "application/json",
        });
        assert.body(() => typia.assert(input));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}

/**
 * @controller ShoppingAdminSystematicChannelsController.update
 * @path PUT /shoppings/admins/systematic/channels/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
    connection: IConnection,
    id: string & Format<"uuid">,
    input: update.Input,
): Promise<void> {
    return !!connection.simulate
        ? update.simulate(
              connection,
              id,
              input,
          )
        : PlainFetcher.fetch(
              {
                  ...connection,
                  headers: {
                      ...(connection.headers ?? {}),
                      "Content-Type": "application/json",
                  },
              },
              {
                  ...update.METADATA,
                  path: update.path(id),
              } as const,
              input,
          );
}
export namespace update {
    export type Input = Primitive<IShoppingChannel.ICreate>;

    export const METADATA = {
        method: "PUT",
        path: "/shoppings/admins/systematic/channels/:id",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (id: string & Format<"uuid">): string => {
        return `/shoppings/admins/systematic/channels/${encodeURIComponent(id ?? "null")}`;
    }
    export const simulate = async (
        connection: IConnection,
        id: string & Format<"uuid">,
        input: update.Input,
    ): Promise<void> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(id),
            contentType: "application/json",
        });
        assert.param("id")(() => typia.assert(id));
        assert.body(() => typia.assert(input));
    }
}

/**
 * @controller ShoppingAdminSystematicChannelsController.merge
 * @path DELETE /shoppings/admins/systematic/channels/merge
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function merge(
    connection: IConnection,
    input: merge.Input,
): Promise<void> {
    return !!connection.simulate
        ? merge.simulate(
              connection,
              input,
          )
        : PlainFetcher.fetch(
              {
                  ...connection,
                  headers: {
                      ...(connection.headers ?? {}),
                      "Content-Type": "application/json",
                  },
              },
              {
                  ...merge.METADATA,
                  path: merge.path(),
              } as const,
              input,
          );
}
export namespace merge {
    export type Input = Primitive<IRecordMerge>;

    export const METADATA = {
        method: "DELETE",
        path: "/shoppings/admins/systematic/channels/merge",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/shoppings/admins/systematic/channels/merge`;
    }
    export const simulate = async (
        connection: IConnection,
        input: merge.Input,
    ): Promise<void> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(),
            contentType: "application/json",
        });
        assert.body(() => typia.assert(input));
    }
}

/**
 * @controller ShoppingAdminSystematicChannelsController.hierarchical
 * @path PATCH /shoppings/admins/systematic/channels/hierarchical
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function hierarchical(
    connection: IConnection,
    input: hierarchical.Input,
): Promise<hierarchical.Output> {
    return !!connection.simulate
        ? hierarchical.simulate(
              connection,
              input,
          )
        : PlainFetcher.fetch(
              {
                  ...connection,
                  headers: {
                      ...(connection.headers ?? {}),
                      "Content-Type": "application/json",
                  },
              },
              {
                  ...hierarchical.METADATA,
                  path: hierarchical.path(),
              } as const,
              input,
          );
}
export namespace hierarchical {
    export type Input = Primitive<IShoppingChannel.IRequest>;
    export type Output = Primitive<IPage<IShoppingChannel.IHierarchical>>;

    export const METADATA = {
        method: "PATCH",
        path: "/shoppings/admins/systematic/channels/hierarchical",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/shoppings/admins/systematic/channels/hierarchical`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Primitive<IPage<IShoppingChannel.IHierarchical>> =>
        typia.random<Primitive<IPage<IShoppingChannel.IHierarchical>>>(g);
    export const simulate = async (
        connection: IConnection,
        input: hierarchical.Input,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(),
            contentType: "application/json",
        });
        assert.body(() => typia.assert(input));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}

/**
 * @controller ShoppingAdminSystematicChannelsController.at
 * @path GET /shoppings/admins/systematic/channels/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
    connection: IConnection,
    id: string & Format<"uuid">,
): Promise<at.Output> {
    return !!connection.simulate
        ? at.simulate(
              connection,
              id,
          )
        : PlainFetcher.fetch(
              connection,
              {
                  ...at.METADATA,
                  path: at.path(id),
              } as const,
          );
}
export namespace at {
    export type Output = Primitive<IShoppingChannel>;

    export const METADATA = {
        method: "GET",
        path: "/shoppings/admins/systematic/channels/:id",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (id: string & Format<"uuid">): string => {
        return `/shoppings/admins/systematic/channels/${encodeURIComponent(id ?? "null")}`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Primitive<IShoppingChannel> =>
        typia.random<Primitive<IShoppingChannel>>(g);
    export const simulate = async (
        connection: IConnection,
        id: string & Format<"uuid">,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(id),
            contentType: "application/json",
        });
        assert.param("id")(() => typia.assert(id));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}

/**
 * @controller ShoppingAdminSystematicChannelsController.get
 * @path GET /shoppings/admins/systematic/channels/:code/get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
    connection: IConnection,
    code: string,
): Promise<get.Output> {
    return !!connection.simulate
        ? get.simulate(
              connection,
              code,
          )
        : PlainFetcher.fetch(
              connection,
              {
                  ...get.METADATA,
                  path: get.path(code),
              } as const,
          );
}
export namespace get {
    export type Output = Primitive<IShoppingChannel>;

    export const METADATA = {
        method: "GET",
        path: "/shoppings/admins/systematic/channels/:code/get",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (code: string): string => {
        return `/shoppings/admins/systematic/channels/${encodeURIComponent(code ?? "null")}/get`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Primitive<IShoppingChannel> =>
        typia.random<Primitive<IShoppingChannel>>(g);
    export const simulate = async (
        connection: IConnection,
        code: string,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(code),
            contentType: "application/json",
        });
        assert.param("code")(() => typia.assert(code));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}